<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GAC.Domain\GAC.Domain.csproj" />
    <ProjectReference Include="..\GAC.Infrastructure\GAC.Infrastructure.csproj" />
  </ItemGroup>

</Project>
