<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GAC.IntegrationSolution.FilePoller-f00d696c-30ab-4f77-a082-e4b4db3c6c95</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	  <Content Include="SampleFiles\**\*.*">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
    <PackageReference Include="Cronos" Version="0.10.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Polly" Version="8.5.2" />
    <PackageReference Include="Quartz" Version="3.14.0" />
    <PackageReference Include="SSH.NET" Version="2025.0.0" />
  </ItemGroup>
</Project>
